### ISSUE TITLE
Installation creates 7800 Registry entries. Yo, wat?!

### ISSUE THREAD

**Issue by Darthagnon** [damienleroy/PowerAccent#66]
## Additional context
- Version: Installed v1.2.3, then installed latest v1.3.3 expecting it to update/overwrite. It did not.
- Which tool: PowerAccent

## Describe the bug and how to reproduce it
Uninstalled v1.2.3 using [Hibit Uninstaller](http://hibitsoft.ir/Uninstaller.html), and it listed 7825 entries in the Windows Registry associated with PowerAccent (obviously I couldn't read them all, but after a cursory scroll-through, looks like all were associated with PowerAccent). That seems a bit excessive.

Also, the installers don't seem to update previous versions, but install alongside them, and they don't record the correct version number in the uninstallation entry (always v0.0.1)

## Screenshot
![HiBitUninstaller-Portable_fenhDT4kDj](https://user-images.githubusercontent.com/20792748/194443965-9df6edc9-080c-42a4-8327-c4b76026170a.png)

**Comment by Darthagnon** [comment]
Here's the log file; seems a bit ridiculous:
[L_07-10-2022_01,59,55.txt](https://github.com/damienleroy/PowerAccent/files/9729801/L_07-10-2022_01.59.55.txt)
This is from a monitored installation of v1.3.3 with Hibit Uninstaller.

**Comment by damienleroy** [comment]
Ok thanks to up this. Indeed it is a big one. And should be related to the [WixToolset](https://wixtoolset.org/).

**Comment by damienleroy** [comment]
Hellom
So I checked the installer and everything seems fine. Multiply installation will not added more unnecessary information in the registry and files.

I can say 2 things about the report:
- A lot of "binary data" `CURRENT_USER\Software\Microsoft\Office\16.0\Common\ExperimentConfigs\Ecs\excel\ConfigContextData` related to excel is in your report, but not related to PowerAccent. Something wrong with the report, and it is the heavier part.
- On my side I count arround 600 entries (files & registry). Which is still some, and I'm sure it can be improve in the installation process. But currently not an issue. Therefore it is possible a previous installation, added a lot of data, and fixed in an update.

Don't hesitate to reopen the issue if the issue still persisting. Thanks
