### ISSUE TITLE
Comparison with similar tool "SymWin"

### ISSUE THREAD

**Issue by Darthagnon** [damienleroy/PowerAccent#8]
SymWin does the same thing as PowerAccent and originally made by @mjvh80 in 2018. [Here's my fork with a couple of minor updates and binaries](https://github.com/Darthagnon/SymWinBinaries). 

I'm not a professional C# developer, but there might be some ideas in the code for you. It currently supports every key on the keyboard, for which many accents and special symbols, approximately by usage for me (English/French/Spanish/Portuguese speaker) on an "average" of a UK (mine) and US (standard) keyboard. It uses CAPSLOCK as the activator key, using multiple presses of the character to type the accent.

**Comment by Darthagnon** [comment]
Having tested your implementation, it's definitely more responsive (the menus on SymWin have poor performance, no idea why). 

I'm still not sure whether I préfer CAPSLÔCK as the äçcent key or space. 

SymWin has the same problem with guessing caret position in browsers, but I do prefer its slightly-higher-than-center default position.

SymWin uses less RAM initially (usage grows with time/accents loaded)

**Comment by damienleroy** [comment]
Did not know about this tool. Will see what it is able to do :)
I've also got some improvement on my side ongoing to get a lot more possibility with choosing countries.

CAPSLOCK is a bad idea in PowerAccent, because it use to Uppercase the typed letters.

@Darthagnon slightly-higher-than-center can be an improvement if you wish.

About RAM, I know PowerAccent take a bit, it is because of the technology I am using (WPF). But it is the best I can use for now to have something that works. And so it is not my priority for now.
