### ISSUE TITLE
Accent combiner

### ISSUE THREAD

**Issue by Mahfoudh94** [damienleroy/PowerAccent#81]
## How it works
like in AZERTY keyboard, you may press a modifier key which is supposed to be printed but it doesn't, why? because it waits for a next letter that may be modified like typing **`** then **e** would result into printing **è** directly, but it is kinda ugly and inefficient.
we can do it like: type  **:a** then pressing a keyboard shortcut (alt+c for example) and it would become **ä**

## Additional settings
- adding the type accent before - after - before & after the letter to accumulate
- ability to have a shortcut  to show all accents already available
- a menu / json file to add custom shortcuts to custom letters

**Comment by damienleroy** [comment]
Hello, yes it was something spoke in another issue. But it will not apply. The reason is because it will ask to rewrite completly the tool and change the behavior, for a minority of people. The current way is simpler for most of user I think.

I can also add you're proposal is a bit more complicated technically speaking, because depending of the keyboard layout the different 'accents' can not be reachable in a same way, so it demand a configuration for each layout (of the world), which is very complicated.

Anyway, thanks for your proposal, it's appreciated :)

**Comment by Mahfoudh94** [comment]
ok, thank you too for thinking of it.

**Comment by Jay-o-Way** [comment]
(off -topic: if it's not going to happen, you could also "close as not planned")
